// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FIS.USESA.POC.Plugins.Interfaces.Entities.Kafka
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class EventKey : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"EventKey\",\"namespace\":\"FIS.USESA.POC.Plugins.Interfaces." +
				"Entities.Kafka\",\"fields\":[{\"name\":\"eventGuid\",\"type\":\"string\"}]}");
		private string _eventGuid;
		public virtual Schema Schema
		{
			get
			{
				return EventKey._SCHEMA;
			}
		}
		public string eventGuid
		{
			get
			{
				return this._eventGuid;
			}
			set
			{
				this._eventGuid = value;
			}
		}

		public override string ToString()
		{
			return $"eventGuid: {eventGuid}";
		}

		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.eventGuid;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.eventGuid = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
